### ISSUE TITLE
关于编译内核的问题

### ISSUE THREAD

**Issue by wbs306** [YuKongA/device_xiaomi_rubens#1]
你好, 请问这个device tree在编译内核的时候有问题吗? 我的device一直在报没有内核源码的错误, 即使设置了`TARGET_FORCE_PREBUILT_KERNEL := true` 也不行, 我的设备是Note 11T Pro, 因为和K50同一个soc就想问问

**Comment by YuKongA** [comment]
事实上我只是开了坑，还没试实际开始搞，甚至不一定真的搞下去。我的手机之前搞 TWRP 的时候换了主板，21天才能解锁。

**Comment by wbs306** [comment]
> 事实上我只是开了坑，还没实际开始搞，甚至不一定真的搞下去。我的手机之前搞 TWRP 的时候换了主板，21 天才能解锁。 且联发科的试错成本太高，特别容易寄，最好 手持售后账号 或者 售后就在边上 再尝试搞这些东西。 另外如果你死在 B 槽位，那么现在的联发科深刷工具就没有任何用了，只能换主板。

好家伙, 我还是第一次接触联发科的设备, 我开始慌了😂
