### ISSUE TITLE
gsi-key.mk does not exist

### ISSUE THREAD

**Issue by Qiaijueqing** [YuKongA/device_xiaomi_rubens#8]
@Ichigokano  Pull the arrow source code and compile according to your compilation guidance, luanch after prompting gsi-key.mk does not exist, what step did I miss? Can you give me more detailed guidance? I would be very grateful

**Comment by zeronao** [comment]
Refer this commit.
https://github.com/kleidione/device_xiaomi_veux/commit/2a86e54bd722da7fb87e51d17dbc88823e84709f
